---
title: "HW1_r"
output: pdf_document
date: "2026-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# read in data
data <- read.csv("evs.csv", stringsAsFactors = TRUE)

# one hot encode data
onehot_data <- model.matrix(~ ., data = data)[, -1]

onehot_data <- as.data.frame(onehot_data)
head(onehot_data)
```

```{r}
# convert data to matrix
numpy_data <- as.matrix(onehot_data)
dim(numpy_data)
```

```{r}
# separate X and y features
y <- numpy_data[, 2]
n_cols <- ncol(numpy_data)
X <- numpy_data[, 3:n_cols]
print(dim(X))
print(length(y))
```

```{r}
# min-max scale the data
library(scales)
X_scale <- apply(X, 2, function(x) rescale(x, to = c(0, 1)))
head(X_scale)
```

```{r}
# add bias term
X_bias <- cbind(1, X_scale)

dim(X_bias)
```

```{r}
# train/test split
set.seed(42)

train_size <- floor(0.7 * nrow(X_bias))
train_idx <- sample(seq_len(nrow(X_bias)), size = train_size)

X_train <- X_bias[train_idx, ]
X_test  <- X_bias[-train_idx, ]
y_train <- y[train_idx]
y_test  <- y[-train_idx]

cat("(", dim(X_train), "), (", dim(X_test), "), (", length(y_train), ",), (", length(y_test), ",)")
```